### ISSUE TITLE
Allow position comment initially

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/pgn-parser#34]
It is handy to have the option to have a comment on the initial position, especially if that comment defines arrows and circles. This should be even allowed for pgnBoard, without any moves, and would therefore allow to have the graphical support to show some playing situations.

An example call could be:

    PGN.pgnBoard('board', { theme: 'zeit', pgn: "{ [%csl Gd5,Gf5,Ye5,Yc5][%cal Ge2e4,Rf2f4] }" })

**Comment by LTe** [comment]
I think there is some misunderstanding about position of comments.

`{before move number} 1. {before first half move} e5 {after first half move} e6 {after move} 2. {before move} Nc3`

As you can see there few positions of comments:

* before move number
* before first half move
* after first half move
* after move

But in really there is only 3 types:

* before first half move
* after first half move
* after move

Why? Because `before move number` it only present **BEFORE** game. In the middle of game `after move` is `before move number`. They are indistinguishable.

Do you know what I mean?

**Comment by mliebelt** [comment]
You are right. But in my opinion, this is different to what I stated above. I want to have at least one comment for to allow arrows and circles before the game starts. And yes, you are right.

So in a different ticket, I would like to address the following:

* Change the existing 3 comments per half move to only one.
* Add the game comment (comments before the game starts) to compensate for having no before move comment.

I don't need to differentiate between black and white, that is the same. But as I said, this is something for a different issue, and it will be a breaking change. I would like to first have a game comment, and when that works well, there is no need any more for a before move comment.

**Comment by mliebelt** [comment]
Changed grammar, so gameComment will  consume the comment before the first moves.
