### ISSUE TITLE
Parsing multiple games without whitespace between games

### ISSUE THREAD

**Issue by pedro-pedrosa** [mliebelt/pgn-parser#43]
I have ran into an issue where parsing multiple games in a single pgn string is not working if there is no whitespace between the two games.

e.g.
```
[Event "name"]
[Site ""]
[Result "*"]
[UTCDate "2021.03.08"]
[UTCTime "10:30:52"]
[Variant "Standard"]
[ECO "C57"]
[Opening "Italian Game: Two Knights Defense, Fried Liver Attack"]
[Annotator ""]

1. e4 e5 *[Event "name2"]
[Site ""]
[Result "*"]
[UTCDate "2021.03.08"]
[UTCTime "10:30:52"]
[Variant "Standard"]
[ECO "C57"]
[Opening "Italian Game: Two Knights Defense, Fried Liver Attack"]
[Annotator ""]

1. e4 e5 *
```

Looking at the [spec](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm) there is no mention of whitespace at the end of the move list or between two consecutive games, so I believe the issue is in the parser not in the formatter.

**Comment by mliebelt** [comment]
You are right. Spec-wise, that is legal (but stupid). Why not including a newline, space, whatever?

Anyway, the fix is easy, and I will include it soon. Will provide a new version then.

**Comment by pedro-pedrosa** [comment]
I cannot control the formatter unfortunately. thanks for looking into it

**Comment by mliebelt** [comment]
Ok, no easy fix. When having changed the grammar from

`tail:(wsp m:game { return m; })*`

to 

`tail:(ws m:game { return m; })*`

the build of the grammar leads to the following error:

    node_modules/pegjs/bin/pegjs --allowed-start-rules pgn,tags,game,games -o _pgn-parser.js src/pgn-rules.pegjs

    34:15: Possible infinite loop when parsing (repetition used with an expression that may not consume any input).
    npm ERR! code 1

So what is the problem?

* The tag section may be empty.
* The pgn section may be empty.
* No whitespace required, so nothing consumed.
* ==> Leads to a (possible) infinite look in parsing.

So found https://github.com/xored/peg/blob/master/docs/grammar-tips.md that explains the problem, but there is no simple fix to it. So no new version today, have to think about something else (and don't want to change the grammar due to that ... worked pretty well for millions of games parsed with it).

**Comment by pedro-pedrosa** [comment]
well, _something_ has to exist, right? either the tags or the pgn. I don't have a lot of experience with grammars but does it make sense to have a game be defined as either `tags ws pgn` or `tags` or `pgn`?

I guess for now I'll have to pre-parse the file somehow.maybe find `\n\n` and look at a tag from the end of that line, if it exists, and add a newline right before it.

**Comment by mliebelt** [comment]
I have a first solution, but found other degradation then. Have to check that first, if possible in some hours.

**Comment by mliebelt** [comment]
Hopefully the new version is sufficient for this part, see the new bug filed #44  about strange cases possible

**Comment by pedro-pedrosa** [comment]
thank you for looking into this!
