### ISSUE TITLE
Parsing null moves

### ISSUE THREAD

**Issue by jiri-matejka** [mliebelt/pgn-parser#436]
I have some PGN files exported from Chessbase, which contains a 'Z0'. It [seems](https://lichess.org/forum/lichess-feedback/feature-request-insert-null-moves-in-studies) to denote a null move in Chessbase PGN files.

I am not a chess player, but from what I studied this is illegal in chess, and thus outside of PGN standard, but sometimes used to demonstrate ideas when teaching.

Is there any chance of supporting this in the parser? With an option for example?

To be more specific, I am getting this error from parser: 
Expected "O-O", "O-O-O", "x", [RNBQKP], [a-h], or whitespace but "Z" found.

There is a similar feature request in [lichess.org repository](https://github.com/lichess-org/lila/issues/10127).

**Comment by mliebelt** [comment]
Interesting. I understand the idea, and would have liked to have that in the past as well. I think, the addition to the parser is quite simple. More complicated is to have the other tools understand what a null move is, and to handle them "the right way". But I like that idea, and I would like to see something like that, so that at least in variants, you could play through some moves, without making dumb moves for the other color which are not relevant.

So to get it right, the idea for tools like pgn-reader/pgn-viewer would be:

* When reading a null move, insert that into the move list in the "right way".
* When playing a null move, just do nothing, but ensure that the other color has the next move.
* When editing a game, allow null moves at any time, and record them. (This is the more complicated part I think, and sure will be the last one.)

**Comment by mliebelt** [comment]
I will provide a new version that implements that feature request to have then a version to play with in the pgn-reader/-viewer.
