### ISSUE TITLE
Parsing fails when date format is incorrect

### ISSUE THREAD

**Issue by Nandakumar-M** [mliebelt/pgn-parser#58]
Hi,

A PGN with wrong format for the 'Date' tag failed to parse in the latest version of pgn-parser.

`[Date "8???.?."]
`
The same pgn used to get parsed successfully in 1.2.0 version.

I guess this is due to stricter checking implemented as part of #46 

Is it possible to not fail on parsing when the Date format is incorrect?

I understand that the parser is not at fault here. Just want to know if a lenient mode is possible where the parser tries to extract as much information as possible but ignores such errors.

Some popular PGN viewers like chesstempo, lichess parsed the pgn ignoring the error in Date field.

Regards,
Nanda

**Comment by mliebelt** [comment]
Yes, your analysis is correct. I was lately more busy fixing bugs in `PgnViewerJS`, and therefore did not try to work on the parser. It is pretty simple to do a custom build, of course, but this is not how you want  to work with it.

The problem here is all the time, that any wrong usage in any game will break the parsing / import of the games. If you are too sloppy in reading them, you won't be able to use it afterwards. It is a tradeoff.

Currently, there is no easy fix. If you clone the repo, and replace the following line

`	/ dateKey ws value:date  { return { name: 'Date', value: value }; }
by

`	/ dateKey ws value:string  { return { name: 'Date', value: value }; }`

and build it then (`npm run-script build`), it should work. I cannot say when I will be able to have a "better solution" (whatever that would be) available.

**Comment by mliebelt** [comment]
Made an exercise, to get this working again, not yet finished, but seems doable. I want to combine your problem with the overall problem to have a more robust parser. I hope I can publish something soon, that works (again) for you.

**Comment by mliebelt** [comment]
Committed the current state, will later finish work on current things and make a new version then.
