### ISSUE TITLE
Ignores FEN turn -> Always sets first move turn as "w"

### ISSUE THREAD

**Issue by ivanpaq** [mliebelt/pgn-parser#62]
When parsing a game that starts from a FEN position, always sets first move turn to White, ignoring FEN information. 

A simple example:

Original PGN:

```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "A"]
[Black "B"]
[Result "0-1"]
[FEN "4r2k/p1p3rp/1p3B2/8/2P2P2/PP1Q1P1q/7P/6RK b - - 0 1"]

1... Qg2+ 2. Rxg2 Re1+ 3. Qf1 (3. Rg1 Rexg1#) 3... Rxf1+ 4. Rg1 Rfxg1# 0-1
```

Example code:

```javascript
var pgnGame = parser.parse('[Event "?"] [Site "?"] [Date "????.??.??"] [Round "?"] [White "A"] [Black "B"] [Result "0-1"] [FEN "4r2k/p1p3rp/1p3B2/8/2P2P2/PP1Q1P1q/7P/6RK b - - 0 1"] 1... Qg2+ 2. Rxg2 Re1+ 3. Qf1 (3. Rg1 Rexg1#) 3... Rxf1+ 4. Rg1 Rfxg1# 0-1', {startRule: "game"})`
console.log(pgnGame);
```

Console Output:

![image](https://user-images.githubusercontent.com/84863832/119695391-666bcf00-be4e-11eb-96f5-eaa8f2fc77b1.png)

With the startRule "games" happens the same (which is how I discovered the issue).

Thanks a lot for your amazing work!

Edit: Added [Bug] Pseudolabel in the title

**Comment by mliebelt** [comment]
This is absolutely correct, and the reason is quite simple: the parser is a parser that does not check if everything is consistent. The result is kind of a parse tree, that is then interpreted by others (like pgn-reader, part of pgn-viewer) which then corrects it. As you may have seen, the parser does not know anything about chess. Here is an edge case, that says, by reading the FEN (which is not interpreted either, just read), the parser could "see" that black is to move.

The specification makes no difference in move number or any other aspect, so black moves can be white moves and white versae. Only the interpretation later by the reader, XOR the interpretation of the FEN string could decide that earlier.

Not so easy to fix that. Have a look at [this line in the reader](https://github.com/mliebelt/PgnViewerJS/blob/d06a54843eef93018a45d754e30d5e4912a83ab9/modules/pgn-reader/src/pgn.js#L343) which does exactly what you want.

What can be done here?

1. Have the parser validate the result somehow (I am thinking of this in the context to be more robust, and reading everything that is possible, but giving the user the option to decide if that is ok or not, see [a discussion I wanted to start](https://github.com/mliebelt/pgn-parser/discussions/61#discussioncomment-777622) which is similar).
2. Define what should be validated without too much hazle: tags, FEN, else? (there should be no chess logic included)
3. Return a much cleaner and more correct parse tree.

**Comment by mliebelt** [comment]
I checked the grammar again, and there is `pgnWhite` and `pgnBlack`, but without any difference besides the setting of `move.turn = 'w'` (or `'b'`). So the grammar could be shorter, no setting of turn, but interpreting afterwards, who had the first turn.

**Comment by ivanpaq** [comment]
First of all, thanks for your quick response :)

OK, so, if I have understood it correctly, the aim of the project is to have a "pure" pgn parser, who doesn't need to know anthing about chess, but is able to parse a PGN file that is consumed by others applications, that makes sense!

Having that in mind, I can see your dilemma for implementing a "valid" solution. My opinion is that the overall goal has to be to provide accurate information as an output, therefore, if `move.turn` information is provided, it has to be 100% correct, or then not to be provided at all.

Despite it, I also think, that a right "parser" should provide at least the same information as the original file provided (data integrity), and if you "visually" check a PGN file, you can see at any moment which player turn is (since it provides the number of the move and the move, so you quickly know if it is white or black turn at any given move), so, getting rid of the `move.turn` field and moving that responsability to the third-party app that consumes the pgn-parser doesn't look like the best way to go for me.

At the end, **it is information that you need from the parser, not only the move itself but also, which player executed it**. At least, unless you are thinking about performance, and you want to have an extremely fast pgn-parser... (but at the end the other app will have to do the calculation and probably not in the more efficient way)

In any case, as a solution, and as you said, I think the best way is to check the FEN to see if it's black or white to move and then set the `move.turn` to `'w'` or `'b'` correctly in each place.

In any case, this is just my opinion, you can ignore it, i'm just trying to help or at least give some food for thoughts :)

BTW, thanks for pointing out the solution from the pgn-reader. I'm going, at least for now, to use that same solution.

PS: You're welcome, there is a lot of value in this work and i'm happy to help.

**Comment by mliebelt** [comment]
Some remarks

I will remove the misleading information `turn` in all cases, and see, if a post-processing step of the parser can add it then correct.
> if you "visually" check a PGN file, you can see at any moment which player turn is (since it provides the number of the move and the move)

See the [spec about move numbers](https://github.com/mliebelt/pgn-spec-commented/blob/main/pgn-specification.md#8221-import-format-move-number-indications). The following is valid PGN, therefore move numbers are not appropriate to distinguish white and black moves.

`1... e4 2. e5 Nf3 3. Nc6`

Of course, the move numbers are wrong, but you are able to import the above PGN into Lichess, and it is corrected then. Without chess knowledge, you cannot say if e4 is a white or black move.

**Comment by mliebelt** [comment]
Restructured the parser, added post-processing, and correct there the wrong turn set. So the turn of each move should be correct for

* A PGN (no tags), where white starts from the starting position.
* A PGN (no tags), but with additional option `fen: "<FEN STRING>"` given to the parser. Handles white and black equally well.
* A PGN with tags, where FEN is correct set.
